### ISSUE TITLE
Сomplete project reworking

### ISSUE THREAD

**Issue by malec-palec** [arthuro555/gdcore-tools#4]
Hi, @arthuro555

Once you mentioned that you were working on a full project rewriting
here https://github.com/arthuro555/gdcore-tools/pull/3#issuecomment-1654665348

Any progress so far? When do you expect roughly to see results?

I'd be happy to help with testing and using the solution.

**Comment by arthuro555** [comment]
I think I had it mostly done locally on my computer but I completely forgot about it 😓 I'll need to look into it sometime

**Comment by arthuro555** [comment]
Little update: I finally powered through the rework, it is done and you can check it out on [branch `2.0.0`](https://github.com/arthuro555/gdcore-tools/tree/2.0.0). 

I haven't pushed it out onto master yet because it still needs to be tested, I am especially unsure about whether or not the typings are working properly. I would appreciate if you tried it out to see if it works well for you! It is published on npm under the version number `gdcore-tools@2.0.0-beta1`. Please report any crash, bug or issue with the typings!

(README has not been updated yet, please refer to typescript definitions file for the new API documentation)

**Comment by arthuro555** [comment]
Update: the types were broken, I've updated the package. You can use the tag `@beta` to access the latest beta of the rework.

**Comment by arthuro555** [comment]
Closing, since the rework has been live for over half a year now
